version: "3.5"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"

  frontend:
    stdin_open: true
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
